# This is the configuration file for the Travis-CI continuous integration
# service.
# From http://jekyllrb.com/docs/continuous-integration/travis-ci/
language: ruby
rvm:
- 2.3.3

script:
    - bundle exec jekyll build --config _config.yml,_travis.yml
    - bundle exec htmlproofer ./_site
    # - github-pages health-check

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Use travis-ci's container-based infrastructure for a faster build
sudo: false
